[package]
name = "blockchain"
version = "0.1.0"
authors = ["mattshardman <mattshardman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8.0"
